routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('trabajo','TrabajoController');
Route::resource('avance','AvanceController');
Route::resource('comentario','ComentarioController');
Route::get('avance/crear/{id}', 'AvanceController@crear')->name('creando');
Route::get('avance/mostrar/{id}', 'AvanceController@mostrar')->name('avance.mostrar');
Route::get('consultar/{id}', 'TrabajoController@VerEvidencia')->name('consultarEvidencia');
Route::resource('usuario','UserController');
Route::resource('notification','NotificationController');
Route::put('/estado/{id}', 'UserController@estado')->name('estado');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('avance/registrarAvance/{id}','AvanceController@registrarAvance');
Route::put('trabajo/terminar/{id}','TrabajoController@terminar')->name('terminar');
Route::get('/finalizar/{id}','TrabajoController@finalizar')->name('finalizar');
Route::get('trabajo/ConsultarBitacoras/{id}','TrabajoController@ConsultarBitacoras')->name('consultar');
Route::get('trabajo/VerEvidencia/{id}','TrabajoController@VerEvidencia')->name('ver');
Route::post('/avance/storeComment','AvanceController@storeComment')->name('storeComment');
Route::get('avance/agregarFile/{id}', 'AvanceController@agregarFile')->name('agregarFile');
Route::get('sendEmailReminder','TrabajoController@sendEmailReminder');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/usuario/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="card-header">
                        Crear nuevo trabajo
                </div>
                <div class="card-body">

                {!! Form::open(['route' => 'trabajo.store'])!!}

                    {{ Form::hidden('user_id', auth()->user()->id)}}

                    <div class="form-group">
                        {{       Form::label('parametro1', 'Ingrese nombre del trabajo')     }}
                        {{       Form::text('nombre',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro2', 'Ingrese nombre del estudiante')     }}
                        {{       Form::text('primerEstudiante',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro3', 'Ingrese rut del estudiante')     }}
                        {{       Form::text('primerRut',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro3', 'Ingrese carrera del estudiante')     }}
                        {{       Form::select('carrera', array('Ingeniería en computación e informática' => 'Ingeniería en computación e informática', 'Ingeniería civil en computación e informática' => 'Ingeniería civil en computación e informática', 'Ingeniería de Ejecución en Computación e Informática' => 'Ingeniería de Ejecución en Computación e Informática', 'Ingeniería Industrial' => 'Ingeniería Industrial' ), null, ['class'=>'form-control'])    }}
                    </div>

                    <p><strong>Si solo es un estudiante, dejar los demás estudiantes en blanco.</strong></p>
                    <div class="form-group">
                        {{       Form::label('parametro4', 'Ingrese nombre del estudiante (Opcional*)')     }}
                        {{       Form::text('segundoEstudiante',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro5', 'Ingrese rut del estudiante (Opcional*)')     }}
                        {{       Form::text('segundoRut',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro3', 'Ingrese carrera del estudiante(Opcional*)')     }}
                        {{       Form::text('segundaCarrera',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro6', 'Ingrese nombre del estudiante (Opcional*)')     }}
                        {{       Form::text('tercerEstudiante',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro7', 'Ingrese rut del estudiante (Opcional*)')     }}
                        {{       Form::text('tercerRut',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro3', 'Ingrese carrera del estudiante (Opcional*)')     }}
                        {{       Form::text('terceraCarrera',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro8', 'Ingrese nombre del estudiante (Opcional*)')     }}
                        {{       Form::text('cuartoEstudiante',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro9', 'Ingrese rut del estudiante (Opcional*)')     }}
                        {{       Form::text('cuartoRut',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro3', 'Ingrese carrera del estudiante (Opcional*)')     }}
                        {{       Form::text('cuartaCarrera',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro10', 'Ingrese nombre del profesor guía')     }}
                        {{       Form::text('primerProfesor',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro11', 'Ingrese rut del profesor guía')     }}
                        {{       Form::text('rutPrimerProfesor',null,['class' => 'form-control'])     }}
                    </div>
                    <p><strong>Si solo es un profesor, dejar el siguiente profesor en blanco.</strong></p>
                    <div class="form-group">
                        {{       Form::label('parametro12', 'Ingrese nombre del segundo profesor guía (Opcional*)')     }}
                        {{       Form::text('segundoProfesor',null,['class' => 'form-control'])     }}
                    </div>

                    <div class="form-group">
                        {{       Form::label('parametro13', 'Ingrese rut del segundo profesor guía (Opcional*)')     }}
                        {{       Form::text('rutSegundoProfesor',null,['class' => 'form-control'])     }}
                    </div>


                    <div class="form-group">
                        {{       Form::submit('Guardar', ['class' => 'btn btn-primary'])     }}
                    </div>

                {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/usuario/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12 col-md-offset-2">
            <div class="card">
                <div class="card-header">
                    EDITAR USUARIO
                </div>
                <div class="card-body">
                    {!! Form::model($usuario, ['route' => ['usuario.update', $usuario->id], 'method' => 'PUT']) !!}



                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{$usuario->name}}" placeholder="{{$usuario->name}}" autofocus>
                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{$usuario->email}}" placeholder="{{$usuario->email}}">

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('rol') ? ' has-error' : '' }}">
                            <label for="rol" class="col-md-4 control-label">Rol</label>

                            <div class="col-md-6">
                                
                                 <select class= "form-control" name="rol" id="rol">
                                 <option value="{{$usuario->rol}}">Sin modificar</option>
                                 <option value="Estudiante">Estudiante</option>
                                 <option value="Profesor">Profesor</option>
                                 <option value="Secretaria">Secretaria</option>
                                 <option value="Encargado">Encargado</option>
                                 <option value="Encargad/profesor">Encargado/profesor</option>


                                 </select>
                           
                        </div>


                        


                        <div class="form-group{{ $errors->has('rol_s') ? ' has-error' : '' }}">
                            <label for="rol_s" class="col-md-4 control-label">Especialidad</label>

                            <div class="col-md-6">
                                
                                 <select class= "form-control" name="rol_s" id="rol_s">
                                 <option value="{{$usuario->rol_s}}">Sin modificar</option>
                                 <option value="Estudiante">Estudiante</option>
                                 <option value="Funcionario">Funcionario</option>
                                 </select>
                           
                        </div>
                        @if($usuario->rol ==  "Estudiante" or $usuario->rol ==  "Profesor")
                        <div class="form-group{{ $errors->has('carrera') ? ' has-error' : '' }}">
                            <label for="carrera" class="col-md-4 control-label">Carrera</label>

                            <div class="col-md-6">
                                
                                 <select class= "form-control" name="carrera" id="carrera">
                                 <option value="{{$usuario->carrera}}">Sin modificar</option>
                                 <option value="Ingeniería en computación e informática">Ingeniería en computación e informática</option>
                                 <option value="Ingeniería civil en computación e informática">Ingeniería civil en computación e informática</option>
                                 <option value="Ingeniería de Ejecución en Computación e Informática">Ingeniería de Ejecución en Computación e Informática</option>
                                 <option value="Ingeniería Industrial">Ingeniería Industrial</option>

                                 </select>
                           
                        </div>
                        @endif
                        <div class="form-group{{ $errors->has('rut') ? ' has-error' : '' }}">
                            <label for="rut" class="col-md-4 control-label">Rut</label>

                            <div class="col-md-6">
                                <input id="rut" type="rut" class="form-control" name="rut" value="{{$usuario->rut}}" placeholder="{{$usuario->rut}}">

                                @if ($errors->has('rut'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('rut') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Contraseña</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" value = "{{$usuario->password}}">

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Guardar
                                </button>
                            </div>
                        </div>




              
                  
                  
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/usuario/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class='col-md-8 col-md-offset-2'>
            <div class="card">
                <div class="card-header">
                    Lista de usuarios
                    <a href="{{route('register')}}" style="float:right"class="btn bn-sm btn-primary">Crear</a>
                </div>
            </div>

            <div class="card-body">           
                <table class='table table-striped table-hover'>
                    <thread>
                        <tr>
                            <th>ID</th>
                            <th>Nombre usuario</th>
                            <th>Usuario</th>
                            <th>Rol</th>
                            <th>Acciones</th>
                        </tr>
                    </thread>

                    <Tbody>
                        @foreach($usuarios as $usuario)
                            <tr>
                                @if($usuario->disponible == 1)
                                        <td>{{$usuario->id}}</td>   
                                         <td>{{$usuario->name}}</td> 
                                         <td>{{$usuario->email}}</td> 
                                         <td>{{$usuario->rol}}</td>     
                                         <td>
                                         <a   href="{{route('usuario.show', $usuario->id)}}" class="btn btn-sm btn-primary">Ver</a>
                                         <a  href="{{route('usuario.edit', $usuario->id)}}" class="btn btn-sm btn-primary">Editar</a >

                                        {!! Form::model($usuario, ['route' => ['estado', $usuario->id], 'method' => 'PUT']) !!}
                                            <button class="btn btn-sm btn-danger" onClick="confirmar_accion()">Eliminar</button>
                                        {!! Form::close() !!}

                                    </td>
                                @endif 
                            </tr>    
                                         
                        @endforeach
                                                                     
                    </Tbody>

                </table>
            </div>

        </div>
    </div>


</div>

<script>

function confirmar_accion(){

    return confirm('¿Estás seguro que deseas eliminar este usuario?');

}

</script>

@endsection

resources/views/usuario/show.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12 col-md-offset-2">
            <div class="card">
                <div class="card-header">
                    VER USUARIO
                    <a href="{{route('usuario.edit', $usuario->id)}}" style="float:right" class="btn btn-primary">Editar</a>
                </div>
                <div class="card-body">
                <p><strong>Nombre del usuario: </strong>{{$usuario->name}}</p>
                <p><strong>Email del usuario: </strong>{{$usuario->email}}</p>
                <p><strong>Rol del usuario: </strong>{{$usuario->rol}}</p>
                <p><strong>Función del usuario: </strong>{{$usuario->rol_s}}</p>
                <p><strong>Carrera del usuario: </strong>{{$usuario->carrera}}</p>
                <p><strong>rut del usuario: </strong>{{$usuario->rut}}</p>

               
            </div>
            <a href="{{route('usuario.index')}}" class="btn btn-info">Volver</a>
        </div>
    </div>
</div>

@endsection