routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('trabajo','TrabajoController');
Route::resource('avance','AvanceController');
Route::resource('comentario','ComentarioController');
Route::get('avance/crear/{id}', 'AvanceController@crear')->name('creando');
Route::get('avance/mostrar/{id}', 'AvanceController@mostrar')->name('avance.mostrar');
Route::get('consultar/{id}', 'TrabajoController@VerEvidencia')->name('consultarEvidencia');
Route::resource('usuario','UserController');
Route::resource('notification','NotificationController');
Route::put('/estado/{id}', 'UserController@estado')->name('estado');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('avance/registrarAvance/{id}','AvanceController@registrarAvance');
Route::put('trabajo/terminar/{id}','TrabajoController@terminar')->name('terminar');
Route::get('/finalizar/{id}','TrabajoController@finalizar')->name('finalizar');
Route::get('trabajo/ConsultarBitacoras/{id}','TrabajoController@ConsultarBitacoras')->name('consultar');
Route::get('trabajo/VerEvidencia/{id}','TrabajoController@VerEvidencia')->name('ver');
Route::post('/avance/storeComment','AvanceController@storeComment')->name('storeComment');
Route::get('avance/agregarFile/{id}', 'AvanceController@agregarFile')->name('agregarFile');
Route::get('sendEmailReminder','TrabajoController@sendEmailReminder');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/consultar/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class='col-md-8 col-md-offset-2'>
                <div class="card">
                    <div class="card-header">
                                BITACORAS
                    </div>
                </div>

                <div class="card-body">
                    <table class='table table-striped table-hover'>
                        <thread>
                            <tr>
                                <th>Nombre del Trabajo</th>
                                <th>Estudiante(s)</th>
                                <th>Profesor(es) guía</th>
                                <th>Historial de Registros </th>
                            </tr>
                        </thread>

                        <Tbody>
                        
                        @if (Auth::user()->rol=="Encargado/profesor" || Auth::user()->rol=="Profesor")
                            @foreach($trabajos as $trabajo)
                                    <tr>
                                        <td>{{$trabajo->nombre}}</td> 

                                        @foreach ($estudiantes as $estudiante)

                                            @if($estudiante->id == $trabajo->idPrimerEstudiante)
                                                <td>{{$estudiante->name}}</td>
                                            @endif
                                            @if($estudiante->id == $trabajo->idSegundoEstudiante)
                                                <td>{{$estudiante->name}}</td>
                                            @endif
                                            @if($estudiante->id == $trabajo->idTercerEstudiante)
                                                <td>{{$estudiante->name}}</td>
                                            @endif
                                            @if($estudiante->id == $trabajo->idCuartoEstudiante)
                                                <td>{{$estudiante->name}}</td>
                                            @endif
                                        @endforeach     

                                        @foreach ($profesores as $profesor)

                                            @if($profesor->id == $trabajo->idPrimerProfesor)
                                                <td>{{$profesor->name}}</td>
                                            @endif
                                            @if($profesor->id == $trabajo->idSegundoProfesor)
                                                <td>{{$profesor->name}}</td>
                                            @endif
                                        @endforeach    
                                        <td><a  href="{{route('trabajo.show', $trabajo->id)}}" class="btn btn-sm btn-primary">Ver avances</a></td>
                                    </tr>     
                                @endforeach
                        @endif

                        @if (Auth::user()->rol=="Estudiante")
                            @foreach($trabajos as $trabajo)
                                    <tr>
                                        <td>{{$trabajo->nombre}}</td>  
                                        <td>{{Auth::user()->name}}</td>
                                            
                                        @foreach ($profesores as $profesor)

                                            @if($profesor->id == $trabajo->idPrimerProfesor)
                                                <td>{{$profesor->name}}</td>
                                            @endif
                                            @if($profesor->id == $trabajo->idSegundoProfesor)
                                                <td>{{$profesor->name}}</td>
                                            @endif
                                        @endforeach    

                                        <td><a  href="{{route('consultarEvidencia', $trabajo->id)}}" class="btn btn-sm btn-primary">Ver avances</a></td>
                                        
                                    </tr>     
                                @endforeach
                        @endif


                        </Tbody>

                    </table>
                </div>

            </div>
        </div>

    </div>

@endsection

resources/views/consultar/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class='col-md-8 col-md-offset-2'>
                <div class="card">
                    <div class="card-header">
                                VER HISTORIA DE REGISTROS
                    </div>
                </div>

                <div class="card-body">
                    <table class='table table-striped table-hover'>
                        <thread>
                            <tr>
                                <th>Fecha</th>
                                <th>Autor</th>
                                <th>Evidencia </th>
                            </tr>
                        </thread>

                        <tbody>
                    
                                <td>{{$trabajo->created_at}}</td>
                                <td>{{$usuario->name}}</td>
                                <td>{{$trabajo->id}}</td>

                        </tbody>

                    </table>
                </div>

                <div class="card-body">
                    <table class='table table-striped table-hover'>
                        <thread>
                            <tr>
                                <th>-</th>
                                <th>Avance</th>
                                <th>Evidencia </th>
                            </tr>
                        </thread>

                        <tbody>
                                @foreach($avances as $avance)
                                    <tr>
                                    @if($avance->trabajo_id == $trabajo->id)
                                        <td>-</td>
                                        <td>{{$avance->texto}}</td>
                                        @if($avance->file)
                                            <td>{{$avance->nombre_file}}</td>
                                        @else
                                            <td>No hay evidencia registrada.</td>
                                        @endif
                                    @endif
                                    </tr>
                                @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

    </div>

@endsection